cliutils: Print $* instead of $1
Sometimes one may inadventantly create several arguments from a single
expression wrapped by double quotes (by expanding an array
argument). This change reduces surprise.

diff --git a/modules/cliutils/functions/print_error b/modules/cliutils/functions/print_error
--- a/modules/cliutils/functions/print_error
+++ b/modules/cliutils/functions/print_error
@@ -7,7 +7,7 @@
 
 function print_error
 {
-    echo -E "${RED}Error: $1${RESET}" >&2
+    echo -E "${RED}Error: $*${RESET}" >&2
 }
 
 # Local Variables:
diff --git a/modules/cliutils/functions/print_fatal_error b/modules/cliutils/functions/print_fatal_error
--- a/modules/cliutils/functions/print_fatal_error
+++ b/modules/cliutils/functions/print_fatal_error
@@ -7,7 +7,7 @@
 
 function print_fatal_error
 {
-    echo -E "${BOLD}${RED}Fatal error: $1${RESET}" >&2
+    echo -E "${BOLD}${RED}Fatal error: $*${RESET}" >&2
 }
 
 # Local Variables:
