cliutils: Print safer with echo -E, and capitalize

diff --git a/modules/cliutils/functions/print_error b/modules/cliutils/functions/print_error
--- a/modules/cliutils/functions/print_error
+++ b/modules/cliutils/functions/print_error
@@ -7,7 +7,7 @@
 
 function print_error
 {
-    echo "${RED}error: $1${RESET}" >&2
+    echo -E "${RED}Error: $1${RESET}" >&2
 }
 
 # Local Variables:
diff --git a/modules/cliutils/functions/print_fatal_error b/modules/cliutils/functions/print_fatal_error
--- a/modules/cliutils/functions/print_fatal_error
+++ b/modules/cliutils/functions/print_fatal_error
@@ -7,7 +7,7 @@
 
 function print_fatal_error
 {
-    echo "${BOLD}${RED}fatal error: $1${RESET}" >&2
+    echo -E "${BOLD}${RED}Fatal error: $1${RESET}" >&2
 }
 
 # Local Variables:
